client:
 client: transmission # допустимо qBittorrent или transmission
 host: 192.168.1.20
 port: 9091
 user: transmission
 password: transmisson
do:
 new_path: /data/rutracker/ # id раздачи добавится автоматически из коммента
 regexp: ^https?://rutracker\.org/forum/viewtopic\.php\?t=(\d+)$
