client:
  client: qBittorrent # допустимо qBittorrent или transmission
  host: localhost
  port: 8080
  user: admin
  password: adminadmin
do:
  # test_run: true
  new_path: /data/rutracker/ # id раздачи добавится автоматически из коммента
  regexp: ^https?://rutracker\.org/forum/viewtopic\.php\?t=(\d+)$
